
##############################################
# Parser Settings for Design Compiler
##############################################
---

format_mode: asic

fmax:
  file: log/frequency_search.log
  pattern: "(.*)Highest frequency with timing constraints being met: ([0-9_]+) MHz"
  group_id: 2

cell_area:
  file: report/area.rep
  pattern: "Total cell area:(\\s*)([0-9,.]+)(.*)"
  group_id: 2

total_area:
  file: report/area.rep
  pattern: "Total area:(\\s*)([0-9,.]+)(.*)"
  group_id: 2

comb_area:
  file: report/area.rep
  pattern: "Combinational area:(\\s*)([0-9,.]+)(.*)"
  group_id: 2

noncomb_area:
  file: report/area.rep
  pattern: "Noncombinational area:(\\s*)([0-9,.]+)(.*)"
  group_id: 2

buf_inv_area:
  file: report/area.rep
  pattern: "Buf/Inv area:(\\s*)([0-9,.]+)(.*)"
  group_id: 2

macro_area:
  file: report/area.rep
  pattern: "Macro/Black Box area:(\\s*)([0-9,.]+)(.*)"
  group_id: 2

net_area:
  file: report/area.rep
  pattern: "Net Interconnect area:(\\s*)([0-9,.]+)(.*)"
  group_id: 2

cell_count:
  file: report/utilization.rep
  pattern: "Cell count:(\\s*)([0-9,.]+)(.*)"
  group_id: 2

dynamic_pow:
  file: report/power.rep
  pattern: "\\| Dynamic \\(W\\) (\\s*)\\|(\\s*)([0-9.]+)(.*)"
  group_id: 3

static_pow:
  file: report/power.rep
  pattern: "\\| Device Static \\(W\\) (\\s*)\\|(\\s*)([0-9.]+)(.*)"
  group_id: 3

...
