
##############################################
# Settings for counter example
##############################################
---

# generate the rtl (from chisel for example)
generate_rtl: "true"
generate_command: "sbt 'runMain example.Counter --o=rtl'" # this requires sbt and firtool

# design path, relative to Asterism root directory, not this directory
design_path: "examples/counter_chisel"
rtl_path: "examples/counter_chisel/rtl"

# generated design settings
top_level_file: "counter.sv"
top_level_module: "counter"
clock_signal: "clock"
reset_signal: "reset"

# copy a file into synthesis directory?
file_copy_enable: "false"
file_copy_source: "/dev/null"
file_copy_dest: "/dev/null"

# delimiters for parameter files
use_parameters: "true"
param_target_file: "src/main/scala/counter.scala"
start_delimiter: "new Counter("
stop_delimiter: ")"

# optional target-specific bounds (in MHz) to speed up fmax search
xc7s25-csga225-1:
  fmax_lower_bound: 100
  fmax_upper_bound: 900
xc7a100t-csg324-1:
  fmax_lower_bound: 250
  fmax_upper_bound: 900
xc7k70t-fbg676-2:
  fmax_lower_bound: 500
  fmax_upper_bound: 1650
XFAB180CMOS:
  fmax_lower_bound: 400
  fmax_upper_bound: 700
AMS350CMOS:
  fmax_lower_bound: 60
  fmax_upper_bound: 160
...
