
##############################################
# Settings for counter example
##############################################
---

#rtl path, relative to "architectures" parent directory (Asterism root), not this directory
rtl_path: "examples/counter_vhdl"

top_level_file: "counter.vhdl"
top_level_module: "counter"

clock_signal: "i_clk"
reset_signal: "i_rst"

# copy a file into synthesis directory?
file_copy_enable: "false"
file_copy_source: "/dev/null"
file_copy_dest: "/dev/null"

# delimiters for parameter files
use_parameters: "true"
start_delimiter: "generic ("
stop_delimiter: ");"

# optionnal target-specific bounds (in MHz) to speed up fmax search
xc7s25-csga225-1:
  fmax_lower_bound: 100
  fmax_upper_bound: 900
xc7a100t-csg324-1:
  fmax_lower_bound: 250
  fmax_upper_bound: 900
  architectures: # optionnal architecture-specific bounds
    04bits:
      fmax_lower_bound: 840
      fmax_upper_bound: 860
    08bits:
      fmax_lower_bound: 490
      fmax_upper_bound: 510
    16bits:
      fmax_lower_bound: 475
      fmax_upper_bound: 495
    24bits:
      fmax_lower_bound: 410
      fmax_upper_bound: 430
    32bits:
      fmax_lower_bound: 385
      fmax_upper_bound: 405
    48bits:
      fmax_lower_bound: 325
      fmax_upper_bound: 345
    64bits:
      fmax_lower_bound: 280
      fmax_upper_bound: 300
xc7k70t-fbg676-2:
  fmax_lower_bound: 500
  fmax_upper_bound: 1650
XFAB180CMOS:
  fmax_lower_bound: 400
  fmax_upper_bound: 700
AMS350CMOS:
  fmax_lower_bound: 60
  fmax_upper_bound: 160
...
